# 数组和矩阵相关题目

矩阵相关的题目是真的很绕，而且有很多细节可以抠，写的人脑壳疼。
以下题目均来自《程序员代码面试指南》

## 1 转圈打印矩阵[🐞🐞]
题目：给定一个整形矩阵matrix，请按照转圈的方式打印它。

### 思路
比较容易想到的两种思路：1、定义curRow和curCol记录当前遍历到的行和列；需要考虑只剩一行和只剩一列的情况；2、定义tR、tC、dR和dC定位当前遍历到的子矩阵，一层一层往里缩小范围；也需要单独考虑只剩一行和只剩一列的情况。

In [1]:
def spiralOrderPrint(matrix):
    def traceMatrix(tR, tC, dR, dC):
        # 如果矩阵只有一行
        if tR == dR:
            for i in range(tC, dC + 1):
                ans.append(matrix[tR][i])
        # 如果矩阵只有一列
        elif tC == dC:
            for i in range(tR, dR + 1):
                ans.append(matrix[i][tC])
        else:
            curR, curC = tR, tC
            while curC != dC:
                ans.append(matrix[tR][curC])
                curC += 1
            while curR != dR:
                ans.append(matrix[curR][dC])
                curR += 1
            while curC != tC:
                ans.append(matrix[dR][curC])
                curC -= 1
            while curR != tR:
                ans.append(matrix[curR][tC])
                curR -= 1

    ans = []
    tR, tC, dR, dC = 0, 0, len(matrix) - 1, len(matrix[0]) - 1
    while tR <= dR and tC <= dC:
        traceMatrix(tR, tC, dR, dC)
        tR, tC, dR, dC = tR + 1, tC + 1, dR - 1, dC - 1
    return ans

测试用例

In [9]:
import numpy as np

testArr = np.arange(16).reshape(4,4) + 1
print(testArr)
spiralOrderPrint(testArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[1, 2, 3, 4, 8, 12, 16, 15, 14, 13, 9, 5, 6, 7, 11, 10]

## 2 将正方形矩阵顺时针转动90度[🐞]
题目：给定一个nxn的matrix，把这个矩阵原地旋转90度，要求空间复杂度O(1).

In [12]:
def rotate(matrix):
    def rotate_submatrix(tR, tC, dR, dC):
        times = dC - tC
        for i in range(times):
            temp = matrix[tR][tC + i]
            matrix[tR][tC + i] = matrix[dR - i][tC]
            matrix[dR - i][tC] = matrix[dR][dC - i]
            matrix[dR][dC - i] = matrix[tR + i][dC]
            matrix[tR + i][dC] = temp
        
        
    tR, tC, dR, dC = 0, 0, len(matrix) - 1, len(matrix[0]) - 1
    while tR < dR:
        rotate_submatrix(tR, tC, dR, dC)
        tR, tC, dR, dC = tR + 1, tC + 1, dR - 1, dC - 1

测试用例

In [14]:
import numpy as np

testArr = np.arange(16).reshape(4,4) + 1
print(testArr)
rotate(testArr)
print(testArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]


## 3 之字型打印矩阵[🐞🐞]
题目：给定一个矩阵matrix，按照之字型打印矩阵，要求额外空间复杂度O(1)

### 思路
下面这个解法比较笨，但能实现功能

In [73]:
def printMatrixZigZag(matrix):
    ans = []
    curR, curC = 0, 0
    direction = 0
    while curR != len(matrix) - 1 or curC != len(matrix[0]) - 1:
        # 向右上方运动
        if direction == 0:
            while curR >= 0 and curC < len(matrix[0]):
                ans.append(matrix[curR][curC])
                curR -= 1
                curC += 1
            direction = 1
            if curC < len(matrix[0]):
                curR = 0
            else:
                curR += 2
                curC = len(matrix[0]) - 1
        # 向左下方运动
        else:
            while curR < len(matrix) and curC >= 0:
                ans.append(matrix[curR][curC])
                curR += 1
                curC -= 1
            direction = 0
            if curR < len(matrix) :
                curC = 0
            else:
                curC += 2
                curR = len(matrix) - 1
    ans.append(matrix[len(matrix) - 1][len(matrix[0]) - 1])
    return ans

测试用例

In [74]:
import numpy as np

testArr = np.arange(10).reshape(2,5) + 1
print(testArr)
printMatrixZigZag(testArr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[1, 2, 6, 7, 3, 4, 8, 9, 5, 10]

### 思路2
还可以借鉴前面两题，使用左上角和右下角确定当前矩形的位置，然后依次打印每个矩形的副对角线直至矩形左上角的坐标到达matrix的右下方。

## 4 找到无序数组中最小的k个数[🐞🐞/🐞🐞🐞🐞]
题目：给定一个无序的整型数组arr，找到其中最小的k个数。

要求：如果arr的长度为N，排序后自然可以得到最小的k个数，此时时间复杂度为O(NlogN)。本题要求读者实现时间复杂度为O(Nlogk)和O(N)的方法。

### 思路1：O(Nlogk)解法

In [ ]:
def getMinKNumbers(arr):
    

## 5 需要排序的最短子数组长度
题目：给定一个无序数组arr，求出需要排序的最短子数组长度。

例如：arr=[1,5,3,4,2,6,7]返回4，因为只有[5,3,4,2]需要排序。

In [76]:
import pandas